### ISSUE TITLE
[BUG] Error trying to upload avatar for pilot/mech

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1015]
<strong>Submitted At: </strong>8/4/2020 23:08:42
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Message received when attempting to upload avatars to Pilot Dossier and Mecha:
"ERROR: The "path" argument must be of type string. Received type undefined"
<strong>To Reproduce: </strong>
attempted more than 3x
<strong>Expected behavior: </strong>
Expected to upload images of pilot and mech avatar
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
```
Vue error at [cc-btn]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.parse (path.js:819:5)
    at file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:94:8394
    at file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:2057
    at Object.next (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:2162)
    at file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:1099
    at new Promise (<anonymous>)
    at s (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:873)
    at A (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:94:8266)
    at a.<anonymous> (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:109:776647)```

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
