### ISSUE TITLE
[BUG] Cannot read 'id' & 'theme'

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1590]
<strong>Submitted At: </strong> 8/4/2021 5:49:11<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> "ERROR:   Cannot read property 'Theme' of undefined 
 ERROR:   Cannot read property 'id' of undefined"

First time using the web-app in a while, synced my account, and repeatedly get these errors. Checked the Github for the above keywords and returned nothing.<br><br><strong>Reproduction Steps:<br> </strong> Unknown; had the HORUS theme set last time I used the web-app. Have the 'CORE NPCs' (Version 1.0.4) and 'Long Rim' (Version 1.0.2) content packs active.<br><br><strong>Expected Result:<br> </strong> To not see an 'ERROR' alert each time I change pages.<br><br><strong>Additional Context:<br> </strong> I'm going to be clearing my cache and cookies, though wished to report the bug, as it might show a trend if others are having the same issue.

P.s.
This seemed to work. It seems that old cookies can interfere with the app.<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read property 'id' of undefined
    at a.userID (https://compcon.app/app.bundle.js:198:106227)
    at un.get (https://compcon.app/app.bundle.js:22:26610)
    at un.evaluate (https://compcon.app/app.bundle.js:22:27760)
    at a.userID (https://compcon.app/app.bundle.js:22:29669)
    at a.r (https://compcon.app/app.bundle.js:198:99825)
    at a.t._render (https://compcon.app/app.bundle.js:22:35296)
    at a.i (https://compcon.app/app.bundle.js:22:64441)
    at un.get (https://compcon.app/app.bundle.js:22:26610)
    at new un (https://compcon.app/app.bundle.js:22:26528)
    at t (https://compcon.app/app.bundle.js:22:64455)```

```
Vue error at [e]
TypeError: Cannot read property 'Theme' of undefined
    at a.userTheme (https://compcon.app/app.bundle.js:198:106269)
    at un.get (https://compcon.app/app.bundle.js:22:26610)
    at un.evaluate (https://compcon.app/app.bundle.js:22:27760)
    at a.userTheme (https://compcon.app/app.bundle.js:22:29669)
    at a.created (https://compcon.app/app.bundle.js:198:106325)
    at Ut (https://compcon.app/app.bundle.js:22:11265)
    at Qe (https://compcon.app/app.bundle.js:22:25179)
    at a.t._init (https://compcon.app/app.bundle.js:22:32825)
    at new a (https://compcon.app/app.bundle.js:22:30399)
    at https://compcon.app/app.bundle.js:22:19298```<br>

**Comment by jarena3** [comment]
Same underlying issue as #1642
