### ISSUE TITLE
[BUG] Issue with Exotic Pilot Gear/Equipment

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1776]
<strong>Submitted At: </strong> 12/10/2021 11:35:13<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> After adding a Exotic Pilot Weapon or Gear to a character sheet and reloading, a error noting, "TypeError: Cannot read properties of undefined (reading 'length')" will appear and the Exotic will be a "blanked" from the character sheet. It then cannot be added to the characters active gear while "blanked."<br><br><strong>Reproduction Steps:<br> </strong> Simply add a Exotic Pilot Weapon or Gear to a character sheet and reload (close/open CompCon) and the error appeared when viewing the character sheet. I tested a few Exotics from Wallflower and a Homebrew.<br><br><strong>Expected Result:<br> </strong> No error output and use of Exotic Gear/Weapon<br><br><strong>Additional Context:<br> </strong> I have a couple snips of the error output in CompCon and how it appears when "blanked"<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'length')
    at a.e.truncate (https://compcon.app/app.bundle.js:328:989250)
    at a.i (https://compcon.app/app.bundle.js:328:988244)
    at a.t._render (https://compcon.app/app.bundle.js:22:35296)
    at a.i (https://compcon.app/app.bundle.js:22:64441)
    at un.get (https://compcon.app/app.bundle.js:22:26610)
    at new un (https://compcon.app/app.bundle.js:22:26528)
    at t (https://compcon.app/app.bundle.js:22:64455)
    at a.kn.$mount (https://compcon.app/app.bundle.js:22:64602)
    at init (https://compcon.app/app.bundle.js:22:19337)
    at https://compcon.app/app.bundle.js:22:52509```<br>

**Comment by msprijatelj** [comment]
Having some trouble reproducing this on Firefox, but I *am* seeing a vestigial "Add Exotic Equipment" button right above the "Equip" button when I constrain my browser to Mobile dimensions:
![image](https://user-images.githubusercontent.com/44978587/145643794-11adaeae-4408-4347-935b-5d606310a54b.png)

**Comment by msprijatelj** [comment]
I can confirm that this is happening on Compcon v2.3.5 with the ANTI-ARMOR SIGNATURE WEAPON from wallflower.
