### ISSUE TITLE
[BUG] Cannot create pilot

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1905]
<strong>Submitted At: </strong> 4/13/2022 8:59:00<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Upon clicking "Create Pilot" from the pilot roster, the screen goes blank and an error is thrown.<br><br><strong>Reproduction Steps:<br> </strong> From home screen, click Pilot Roster, then click Create Pilot.<br><br><strong>Expected Result:<br> </strong> Character creation.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: Object(...)(...).UserProfile.GetView is not a function
    at a.quickstart (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:154:1658077)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:30788)
    at rr.evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:31777)
    at a.quickstart (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:33470)
    at a.eb (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:154:1628661)
    at a.e._render (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:30788)
    at new rr (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:30706)
    at Dn (https://d33wubrfki0l68.cloudfront.net/bundles/32d6f8ca8a861e27b3d06caf84ed239da710fb8a.js:7:27917)```<br>

**Comment by jarena3** [comment]
AWS side is choking due to spiked traffic. This'll resolve itself in a few hours.
