### ISSUE TITLE
[BUG] Emperor mech broken

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1910]
<strong>Submitted At: </strong> 4/13/2022 13:14:06<br><br><strong>Source: </strong> The Karrakin Trade Baronies<br><br><strong>Incorrect Text/Data: </strong><br> Attempting to choose the Emperor for a pilot's mech results in an error.<br><br><strong>Correct Text/Data: </strong><br> ```
Vue error at [ee]
TypeError: Cannot read properties of null (reading 'toString')
    at Function.Evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:154:6953)
    at https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:154:6648
    at Array.reduce (<anonymous>)
    at Function.get (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:154:6627)
    at Function.Int (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:154:6430)
    at te.get MaxHP [as MaxHP] (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:154:443325)
    at a.Pf (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:154:1581312)
    at a.e._render (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/dab4dd6b5fa2531d4f37e324a4561a92898201c3.js:7:30788)```<br>

**Comment by jarena3** [comment]
fixed in 3.2.3
