### ISSUE TITLE
[BUG] Skirmish or Barrage with Prototype Weapon/Fuel Rod Gun throws error

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1916]
<strong>Submitted At: </strong> 4/13/2022 20:12:07<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> In active mode, attempting to skirmish with the integrated weapons granted by Engineer or Nuclear Cavalier causes the attack window to appear with no content, and throws the error
"ERROR:   Cannot read properties of undefined (reading 'TalentsController')"<br><br><strong>Reproduction Steps:<br> </strong> * Create a character with Nuclear Cavalier 3 and/or any level of Engineer, create a mech for that character
* Enter active mode and start mission with that character
* Attempt to skirmish or barrage with either the Prototype Weapon or Fuel Rod Gun<br><br><strong>Expected Result:<br> </strong> The attack window loads with the weapon info for the appropriate weapon.<br><br><strong>Additional Context:<br> </strong> Issue doesn't appear to exist for integrated mount weapons from other sources, such as the Barbarossa's Apocalypse Rail<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: Cannot read properties of undefined (reading 'TalentsController')
    at armoryLevel (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:154:1850365)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:30788)
    at rr.evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:31777)
    at a.armoryLevel (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:33470)
    at a (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:154:1832570)
    at a.e._render (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:30788)
    at rr.run (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:31521)
    at Zn (https://d33wubrfki0l68.cloudfront.net/bundles/f6bce1501143b40f0d7627138036ca1d386ff552.js:7:29728)```<br>

**Comment by jarena3** [comment]
fixed in 2.3.3
