### ISSUE TITLE
[BUG] Cannot reset Mech Skills for pilot.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1924]
<strong>Submitted At: </strong> 4/14/2022 22:42:54<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When assigning skill points to HASE stats, attempting to reset the stats with the "RESET MECH SKILLS" button generates an error and does not reset the stats.<br><br><strong>Reproduction Steps:<br> </strong> 1. Create a pilot and open it, or open an existing pilot in COMP/CON
2. Switch to the Tactical Profile tab of the pilot sheet
3. On the MECH SKILLS section of the sheet, press the pencil icon to its left.
4. At the top of the modal that opens, press the RESET MECH SKILLS button.
5. Observe as this message appears and your stats are not set back to 0: "ERROR:   e.pilot.resetHASE is not a function"<br><br><strong>Expected Result:<br> </strong> All four stats (Hull, Agility, Systems, and Engineering) are set back to 0, and no error message is generated for pressing the innocuous reset stats button.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: e.pilot.resetHASE is not a function
    at click (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:140:513908)
    at rt (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:7:11674)
    at a.n (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:7:13494)
    at rt (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:7:11674)
    at a.In.e.$emit (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:7:26570)
    at a.click (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:40:74031)
    at rt (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:7:11674)
    at HTMLButtonElement.n (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:7:13494)
    at HTMLButtonElement.Qi.o._wrapper (https://d33wubrfki0l68.cloudfront.net/bundles/d040891eb4f79a1ace51b8502ecc632612ae0b6b.js:7:52151)```<br>

**Comment by msprijatelj** [comment]
May want to check the other Reset methods that would’ve been moved into Controller classes for the Cloud Update.
