### ISSUE TITLE
[BUG] Cannot read properties of undefined

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1939]
<strong>Submitted At: </strong> 4/16/2022 8:27:59<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> In pilot roster, getting popup "Error: Cannot read properties of undefined (reading "portrait")<br><br><strong>Reproduction Steps:<br> </strong> Go to Pilot Roster<br><br><strong>Expected Result:<br> </strong> No error popup<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'Portrait')
    at a.ka (https://compcon.app/app.bundle.js:343:228371)
    at a.t._render (https://compcon.app/app.bundle.js:22:35296)
    at a.i (https://compcon.app/app.bundle.js:22:64441)
    at un.get (https://compcon.app/app.bundle.js:22:26610)
    at new un (https://compcon.app/app.bundle.js:22:26528)
    at t (https://compcon.app/app.bundle.js:22:64455)
    at a.kn.$mount (https://compcon.app/app.bundle.js:22:64602)
    at init (https://compcon.app/app.bundle.js:22:19337)
    at https://compcon.app/app.bundle.js:22:52509
    at d (https://compcon.app/app.bundle.js:22:52786)```<br>

**Comment by msprijatelj** [comment]
This feels like an issue from version 2.2.35? No version information nor detailed reproduction steps means that this will be difficult to reproduce.

**Comment by jarena3** [comment]
I'm 99% sure you're right. Going to close this one.
