### ISSUE TITLE
[BUG] Website generally not working, throwing errors 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2020]
<strong>Submitted At: </strong> 5/27/2022 0:44:24<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I'm not currently logged in, and attempting to go to the login popup fails to load anything on the popup. Attempting to view an existing pilot in the cache shows a blank dossier. Not blank like the fields are empty but blank as in the entire page below the header is pure white. Deleting cookies, cache, etc does not fix this. Attempting to import from a backup file does not fix this. Attempting to create a new pilot results in an error: "Object(...)(...).UserProfile.GetView is not a function". Attempting to go to the options page on the home screen brings a popup with an error "this.user.getView is not a function". There is no sign that I am logged in at all. <br><br><strong>Reproduction Steps:<br> </strong> This started happening after I refreshed the site and saw the popup about the site being updated. As far as I can tell there was nothing I did to trigger this other than entering the site. <br><br><strong>Expected Result:<br> </strong> I expected to be able to view an existing pilot or create a new one, or login, or any of the functions I've mentioned. <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: this.user.GetView is not a function
    at a.get (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140:1940268)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:30788)
    at rr.evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:31777)
    at a.userSaveStrategy (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:33470)
    at a.o (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:140:1934445)
    at a.e._render (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:30788)
    at new rr (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:30706)
    at Dn (https://d33wubrfki0l68.cloudfront.net/bundles/739af346a9ca242e40d7c3ad1cf0a6760433fa0f.js:7:27917)```<br>

**Comment by jarena3** [comment]
A page reload should take care of this
