### ISSUE TITLE
[BUG] ERROR:   Cannot read properties of undefined (reading 'getTiles')

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2139]
<strong>Submitted At: </strong> 9/29/2022 13:21:28<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Chromebook<br><br><strong>Issue Description: </strong><br> When I'm in an encounter, when I change the status of an NPC, I get the error: ERROR:   Cannot read properties of undefined (reading 'getTiles')

The status does seem to change, however.

The NPCs have been created following the wallflower rules (underslung grenade assault mech etc). I have the LCPs installed for the core and wallflower.<br><br><strong>Reproduction Steps:<br> </strong> Create an encounter with the four mechs and their additions according to the main, first mission mission in Wallflower (escort the engineers). Start the encounter, and try to add a status to an npc.<br><br><strong>Expected Result:<br> </strong> No errors to pop up.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: Cannot read properties of undefined (reading 'getTiles')
    at a.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/ad58da9349b060d30e223f63c79d31cd8fb74b29.js:127:72213)
    at Array.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/ad58da9349b060d30e223f63c79d31cd8fb74b29.js:7:12771)
    at ut (https://d33wubrfki0l68.cloudfront.net/bundles/ad58da9349b060d30e223f63c79d31cd8fb74b29.js:7:12166)```<br>

**Comment by msprijatelj** [comment]
Another PilotNET user claimed that this may be an issue with Chrome. Haven't confirmed yet.
