### ISSUE TITLE
[BUG] Pilots not importing on separate computer

### ISSUE THREAD

**Issue by Sescheraun** [massif-press/compcon#2167]
**Describe the bug**

I am not able to access my pilots on a different computer,

**To Reproduce**
I made my pilot on my home computer and tried to load it as a copy on my work computer but it would not import.

**Expected behavior**
I expected to be able to load my pilot.

**Screenshots**

I do not have a screen shot, but the log is:

a10e2e3be48fc945831e05bc38c275cd62062b34.js:140 
importing as copy
a10e2e3be48fc945831e05bc38c275cd62062b34.js:140 
TypeError: this.Talent.Rank is not a function
    at get UnlockedRanks [as UnlockedRanks] (a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:2035374)
    at a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1791018
    at Array.forEach (<anonymous>)
    at get FeatureSource [as FeatureSource] (a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1790995)
    at a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1811263
    at Array.flatMap (<anonymous>)
    at s.collectAll (a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1811238)
    at get Bonuses [as Bonuses] (a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1811464)
    at Bonus.Int (a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:6276)
    at get Speed [as Speed] (a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:324082)
Deserialize @ a10e2e3be48fc945831e05bc38c275cd62062b34.js:140
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for https://d33wubrfki0l68.cloudfront.net/bundles/app.b4682d6c.js.map;: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
/#/pilot_management:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Desktop (please complete the following information):**
Win 10, Chrome Version 108.0.5359.125 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by msprijatelj** [comment]
@Sescheraun To be clear, which numbered version of CompCon are you using? If you're using something earlier than 2.3.0, please follow [these steps](https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#compcon-is-stuck-on-an-older-version-than-230-how-do-i-update-to-the-latest-version) to force an update. Also, could you please confirm that you are using a cloud account on CompCon?

Otherwise, please make sure that both of your browsers accept incoming connections from AWS, whether that be by whitelisting CompCon + AWS on your browser extensions, or dealing with any issues that may block connections on your work laptop (e.g. if your laptop has a firewall installed by your organization, or something).

Lastly, make sure that all of your LCPs are present on both browsers. Usually LCPs will import automatically from the cloud, but maybe manually installing them on the work computer may help?

**Comment by jarena3** [comment]
this has been resolved in v3
