### ISSUE TITLE
[BUG] NPC and Pilot data not saving.

### ISSUE THREAD

**Issue by de4nge1o** [massif-press/compcon#2193]
**Describe the bug**
As title reads, NPC and pilot data is not saving. This also includes any encounters or missions made in those builders. When I create an NPC, it disappears when I refresh the page. Changes made to pilots reverts as well, such as deleted pilots will return, new pilots will disappear, or edits to pilots will vanish. 

Before this all started happening, I had dozens of NPCs that I had put together for Wallflower. I redownloaded the most recent lcp files for Lancer and Wallflower, including the NPC files. The day after I did this and checked my NPC roster, there were no NPCs.

Two errors appear:
Cannot read properties of undefined (reading '0')
this.user.GetView is not a function

The 1st error appears when I open Comp/Con. The 2nd error appears after I make an edit of any kind to a Pilot.

Comp/Con works as expected in other browsers.

**To Reproduce**

1. Create a new NPC, Pilot, Mission, Encounter, or make edits to existing Pilots.
2. Refresh page.

**Expected behavior**
Data to save. 

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser Chrome
 - Version: Version 110.0.5481.105 (Official Build) (64-bit)

**Stack Trace**

Stack Trace for "Cannot read properties of undefined"
Vue error at [ee]
TypeError: Cannot read properties of undefined (reading '0')
    at new Ee (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:482881)
    at Ee.Deserialize (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:491558)
    at https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:366294
    at Array.map (<anonymous>)
    at Object.LOAD_NPCS (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:366280)
    at v.o (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:40:5094)
    at https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:21:6290
    at https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:21:7324
    at Array.forEach (<anonymous>)
    at https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:21:7303

Stack Trace for "this.user.Getview is not a function"
Vue error at [ee]
TypeError: this.user.GetView is not a function
    at a.get (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1949023)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788)
    at rr.evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:31777)
    at a.userSaveStrategy (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:33470)
    at a.o (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1943169)
    at e._render (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788)
    at new rr (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706)
    at Dn (https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917)

**Comment by tristan-orourke** [comment]
I've been getting the same error.

**Comment by jarena3** [comment]
@de4nge1o @tristan-orourke 
do you have a large amount of installed LCPs?

**Comment by tristan-orourke** [comment]
I do yes. 12 installed LCPs, 10 active. I could definitely remove some of them, if that's causing a problem.

**Comment by jarena3** [comment]
closing this as I think it's solved between the localstorage limits and cloud stuff. If this remains an issue I will create a specific ticket for it post v3-release
