### ISSUE TITLE
Pilot armor missing from gear loadout [BUG] 

### ISSUE THREAD

**Issue by theleonamaple** [massif-press/compcon#2227]
**Describe the bug**
Pilot armor is missing entirely from gear loadout for existing character sheets. For new character sheets, the "pilot armor" section appears but the same error pops up when trying to select an armor option.

I am on compcon 2.3.11.

Short form of error code: ERROR:   Cannot read properties of undefined (reading 'Value')
In the log it says: 
Stack Trace
```
Vue error at [ee]
TypeError: Cannot read properties of undefined (reading 'Value')
    at Bonus.Evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:140:6758)
    at D.Armor (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:140:420581)
    at a (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:140:779788)
    at e._render (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:7:30788)
    at new rr (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:7:30706)
    at Dn (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:7:27917)
    at xr.$mount (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:7:66038)
    at init (https://d33wubrfki0l68.cloudfront.net/bundles/847d714e6de0357dc0e75060de4ecc7e2acbedc1.js:7:20676)```

Desktop
 - OS: Windows 10 Home Edition
Version	21H2
Installed on	‎06/‎10/‎2020
OS build	19044.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

 - Browser 
 Brave Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit)
 AND
Chrome Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by jarena3** [comment]
resolved in hotfix
