### ISSUE TITLE
[BUG] COMP/CON doesn't load Cloud account.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2238]
<strong>Submitted At: </strong> 5/19/2023 4:59:39<br><br><strong>Browser: </strong> Opera<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When I try to log in the A window titled "Could account" appears, that is empty except a "loading" symbol.

If I close the windoe I can open the pilot roster, but if I click a pilot I can't see their pilot or mech sheet. and When I try to open any page of compendium a error appears (I attached it).<br><br><strong>Reproduction Steps:<br> </strong> Opening a new private window.
Clicking "Log in".
Enter e-mail and password.
The message "log in successfull" appears.
The window mentioned above appears.<br><br><strong>Expected Result:<br> </strong> To be able to see the sheet of my character.<br><br><strong>Additional Context:<br> </strong> I already tried loading my local data backup which did not work.<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: this.user.GetView is not a function
    at a.get (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:140:1945430)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:30788)
    at rr.evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:31777)
    at a.userSaveStrategy (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:33470)
    at a.o (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:140:1939546)
    at e._render (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:30788)
    at new rr (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:30706)
    at Dn (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:27917)```<br>

**Comment by MaxPelly** [comment]
This is likely due to the AWS quota having been exceeded  #2237

**Comment by jarena3** [comment]
backend quotas have been increased
