### ISSUE TITLE
Compcon doesn't want to load login [BUG] 

### ISSUE THREAD

**Issue by Maboi000** [massif-press/compcon#2239]
**Describe the bug**
Opening Compcon, the site doesn't want to finish loading my cloud account, it is stuck in the swirling.

**To Reproduce**
It just happens when loading into compcon and doesn't let me save or anything.

**Screenshots**
![image](https://github.com/massif-press/compcon/assets/107842478/ba4ef5b8-cdb9-4853-b694-29c8f6b7e8c5)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Opera GX]
 - Version [CompCon 2.3.15]

Additionally I cannot update Comp/con as the option doesn't appear, so if you wanted to tell me to just update compcon that's not a possibility.

**Comment by Maboi000** [comment]
Found this in the log : 
```
Vue error at [ee]
TypeError: this.user.GetView is not a function
    at a.get (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:140:1945430)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:30788)
    at rr.evaluate (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:31777)
    at a.userSaveStrategy (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:33470)
    at a.o (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:140:1939546)
    at e._render (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:23862)
    at a.r (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:27903)
    at rr.get (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:30788)
    at new rr (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:30706)
    at Dn (https://d33wubrfki0l68.cloudfront.net/bundles/79f7e6b927184ab6566309d97825d9d129737f24.js:7:27917)```

**Comment by jarena3** [comment]
backend quotas have been increased
