### ISSUE TITLE
[BUG] False exotic entries listed in weapon mods

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2364]
<strong>Submitted At: </strong> 1/16/2024 9:14:28<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The exotic system "Bounder-Class Comp/Con" from Winter Scar appears in the Weapon Mods selection screen, despite not possessing the exotic equipment<br><br><strong>Reproduction Steps:<br> </strong> I could not tell you.

The pilot in question is a flash clone of another (Not a typical duplicate, if that matters). The original does not have this issue, and no other flash clone of this pilot does either, even when having the same expected weapon mods available.<br><br><strong>Expected Result:<br> </strong> The Boulder-Class Comp/Con not being there<br><br><strong>Additional Context:<br> </strong> Comp/Con data of the affected pilot can be found here - https://discord.com/channels/426286410496999425/568459736119509023/1196832997794664539<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: Cannot read properties of undefined (reading '0')
    at new Ee (https://compcon.app/js/app.60452014.js:1:496609)
    at Ee.Deserialize (https://compcon.app/js/app.60452014.js:1:505349)
    at https://compcon.app/js/app.60452014.js:1:378970
    at Array.map (<anonymous>)
    at Object.LOAD_NPCS (https://compcon.app/js/app.60452014.js:1:378956)
    at v.o (https://compcon.app/js/chunk-vendors.b4c5b2b8.js:40:5094)
    at https://compcon.app/js/chunk-vendors.b4c5b2b8.js:21:6290
    at https://compcon.app/js/chunk-vendors.b4c5b2b8.js:21:7324
    at Array.forEach (<anonymous>)
    at https://compcon.app/js/chunk-vendors.b4c5b2b8.js:21:7303```<br>

**Comment by tomjel45** [comment]
This is most likely an error in the lcp file itself and not comp/con as third party content can have issues and typos that may otherwise not be the case, third party content is not subject to any standard of quality and winter is currently in its play test phase. This issue is consist with other third party content and is on the shoulders of the author of the lcp, not comp/con.

**Comment by msprijatelj** [comment]
I actually believe this was an oversight on CompCon’s end since most other exotic gear isn’t a Weapon Mod.
