### ISSUE TITLE
[BUG] Error at random

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#771]
<strong>Submitted At: </strong>4/8/2020 0:40:40
<strong>Platform: </strong>
Electron - Linux
<strong>Describe the bug: </strong>
Had been working on testing a variety of things, including creating, synching, exporting, and deleting pilots when I got this error, without any context for what caused it.
<strong>To Reproduce: </strong>
Unknown
<strong>Expected behavior: </strong>
No error
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Unwary#3649
<strong>Stack Trace: </strong>
```
Vue error at [cc-selector-table]
TypeError: Cannot read property 'ItemType' of undefined
    at r.created (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:109:721642)
    at $t (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:11294)
    at Qe (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:25255)
    at r.t._init (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:32901)
    at new r (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:30475)
    at file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:19374
    at init (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:19405)
    at file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:52588
    at d (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:52865)
    at h (file:///tmp/.mount_COMPCOAWLUf4/resources/app.asar/app/app.bundle.js:21:53456)```

**Comment by jarena3** [comment]
I think I've caught this in another change
