### ISSUE TITLE
[BUG] ERROR:   Unexpected token } in JSON at position 196

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#860]
<strong>Submitted At: </strong>5/23/2020 20:16:52
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
mech and pilot profile details not showing up when selected from roster (preview from pilot roster works fine, as does active mode and other methods of dispaying stats)
<strong>To Reproduce: </strong>
no idea. my players exported pilot .json and i imported
<strong>Expected behavior: </strong>
the things to appear. it's a bug.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
chemical mess#5049
<strong>Stack Trace: </strong>
Vue error at [landing-page]
SyntaxError: Unexpected token } in JSON at position 196
    at JSON.parse (<anonymous>)
    at h (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:104:58047)
    at a.beforeMount (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:109:720856)
    at $t (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:21:11294)
    at Qe (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:21:25255)
    at t (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:21:64475)
    at a.kn.$mount (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:21:64681)
    at init (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:21:19413)
    at n (file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:21:23242)
    at file:///C:/Users//AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:21:52588

**Comment by jarena3** [comment]
Following up via discord
