### ISSUE TITLE
[BUG] Black Sheets error

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#916]
<strong>Submitted At: </strong>6/19/2020 19:30:55
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Upon choosing the Print Blank Sheets option an error is thrown, though the blank sheets are produced properly.
<strong>To Reproduce: </strong>
Select "Print" from a character's gear-menu, click the Print Blank Sheets option.
<strong>Expected behavior: </strong>
No error.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
```
Vue error at [combined-print]
TypeError: Cannot read property 'Mechs' of undefined
    at a.created (https://compcon.app/app.bundle.js:97:319663)
    at $t (https://compcon.app/app.bundle.js:22:11265)
    at Qe (https://compcon.app/app.bundle.js:22:25179)
    at a.t._init (https://compcon.app/app.bundle.js:22:32825)
    at new a (https://compcon.app/app.bundle.js:22:30399)
    at https://compcon.app/app.bundle.js:22:19298
    at init (https://compcon.app/app.bundle.js:22:19329)
    at n (https://compcon.app/app.bundle.js:22:23166)
    at https://compcon.app/app.bundle.js:22:52509
    at d (https://compcon.app/app.bundle.js:22:52786)```

**Comment by jarena3** [comment]
Unable to reproduce
