### ISSUE TITLE
[BUG] Broken Image Uploader

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#950]
<strong>Submitted At: </strong>7/5/2020 22:11:39
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
Any attempt to upload a photo for a pilot gives the Error message [ERROR: The "path" argument must be of type string. Recieved type undefined]
<strong>To Reproduce: </strong>
Clicking "Add Image to Collection"
<strong>Expected behavior: </strong>
A file browser would open and allow me to select and upload a photo of my own
<strong>Additional context: </strong>
I was able to upload an image for a pilot on the Browser app and port them over with the image
<strong>Contact Info: </strong>
@SeattleAnon#5701
<strong>Stack Trace: </strong>
```
Vue error at [cc-btn]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.parse (path.js:819:5)
    at file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:94:8394
    at file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:2057
    at Object.next (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:2162)
    at file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:1099
    at new Promise (<anonymous>)
    at s (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:16:873)
    at A (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:94:8266)
    at a.<anonymous> (file:///C:/Users/Owner/AppData/Local/Temp/1cHFwMK9WJJ39kUylYONcaTxwqy/resources/app.asar/app/app.bundle.js:109:776647)```

**Comment by Mischala** [comment]
There is a fix for this in Dev
#951
